// export const C_LOMM_DATA_URL = '../../assets/json/LOMM.json';
export const C_LOMM_CARD_STYLE_URL = 'assets/json/LOMM_CARD_STYLES.json';
export const C_LOMM_DATA_URL = 'assets/csv/chicsv.csv';
export const C_API_URL = 'http://localhost:4200';
export const C_MENU_DATA_URL = 'assets/csv/chi_dashboard_links.csv';
// export const C_QUICK_LINKS = 'assets/json/QUICK_LINKS.json';
export const C_QUICK_LINKS = 'assets/csv/chi_quick_links.csv';
// export const C_HSC_KPI_DATA = 'assets/json/HSC.json';
export const C_HSC_KPI_DATA = 'assets/csv/chi_hsc_data.csv';
